var mongoose = require("mongoose");

var riseOfRedSkullSchema = mongoose.Schema({
  campaignName: { type: String, unique: true },
  playerOne: {
    hero: String,
    techUpgrade: String,
    basicUpgrade: String,
    improved: Boolean,
    rescuedAllies: String,
    hitPoints: String,
    obligationOne: Boolean,
    obligationTwo: Boolean,
    obligationThree: Boolean,
    obligationFour: Boolean,
  },
  playerTwo: {
    hero: String,
    techUpgrade: String,
    basicUpgrade: String,
    improved: Boolean,
    rescuedAllies: String,
    hitPoints: String,
    obligationOne: Boolean,
    obligationTwo: Boolean,
    obligationThree: Boolean,
    obligationFour: Boolean,
  },
  playerThree: {
    hero: String,
    techUpgrade: String,
    basicUpgrade: String,
    improved: Boolean,
    rescuedAllies: String,
    hitPoints: String,
    obligationOne: Boolean,
    obligationTwo: Boolean,
    obligationThree: Boolean,
    obligationFour: Boolean,
  },
  playerFour: {
    hero: String,
    techUpgrade: String,
    basicUpgrade: String,
    improved: Boolean,
    rescuedAllies: String,
    hitPoints: String,
    obligationOne: Boolean,
    obligationTwo: Boolean,
    obligationThree: Boolean,
    obligationFour: Boolean,
  },
  laserRifle: Boolean,
  energyShield: Boolean,
  powerGauntlets: Boolean,
  exoSuit: Boolean,
  numOfDelayCounters: String,
  playerOneEngaged: Boolean,
  playerTwoEngaged: Boolean,
  playerThreeEngaged: Boolean,
  playerFourEngaged: Boolean,
  playerOneAllyRemoved: String,
  playerTwoAllyRemoved: String,
  playerThreeAllyRemoved: String,
  playerFourAllyRemoved: String,
});

var RiseOfRedSkull = mongoose.model("RiseOfRedSkull", riseOfRedSkullSchema);
module.exports = RiseOfRedSkull;

/* username: String,
whiteCount: String,
blueCount: String,
blackCount: String,
redCount: String,
greenCount: String,
multiColorCount: String,
colorlessCount: String,
allColorCount: String,
missTwoCount: String,
fivePlusCount: String,
sixPlusCount: String, */
